// data-science-stack/src/main/webapp/app/entities/area/update/area-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { AreaFormService, AreaFormGroup } from './area-form.service';
import { IArea } from '../area.model';
import { AreaService } from '../service/area.service';
import { ITask } from 'app/entities/task/task.model';
import { TaskService } from 'app/entities/task/service/task.service';
import { IScientist } from 'app/entities/scientist/scientist.model';
import { ScientistService } from 'app/entities/scientist/service/scientist.service';

@Component({
  selector: 'jhi-area-update',
  templateUrl: './area-update.component.html',
})
export class AreaUpdateComponent implements OnInit {
  isSaving = false;
  area: IArea | null = null;

  tasksSharedCollection: ITask[] = [];
  scientistsSharedCollection: IScientist[] = [];

  editForm: AreaFormGroup = this.areaFormService.createAreaFormGroup();

  constructor(
    protected areaService: AreaService,
    protected areaFormService: AreaFormService,
    protected taskService: TaskService,
    protected scientistService: ScientistService,
    protected activatedRoute: ActivatedRoute
  ) {}

  compareTask = (o1: ITask | null, o2: ITask | null): boolean => this.taskService.compareTask(o1, o2);

  compareScientist = (o1: IScientist | null, o2: IScientist | null): boolean => this.scientistService.compareScientist(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ area }) => {
      this.area = area;
      if (area) {
        this.updateForm(area);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const area = this.areaFormService.getArea(this.editForm);
    if (area.id !== null) {
      this.subscribeToSaveResponse(this.areaService.update(area));
    } else {
      this.subscribeToSaveResponse(this.areaService.create(area));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IArea>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(area: IArea): void {
    this.area = area;
    this.areaFormService.resetForm(this.editForm, area);

    this.tasksSharedCollection = this.taskService.addTaskToCollectionIfMissing<ITask>(this.tasksSharedCollection, ...(area.tasks ?? []));
    this.scientistsSharedCollection = this.scientistService.addScientistToCollectionIfMissing<IScientist>(
      this.scientistsSharedCollection,
      area.scientist
    );
  }

  protected loadRelationshipsOptions(): void {
    this.taskService
      .query()
      .pipe(map((res: HttpResponse<ITask[]>) => res.body ?? []))
      .pipe(map((tasks: ITask[]) => this.taskService.addTaskToCollectionIfMissing<ITask>(tasks, ...(this.area?.tasks ?? []))))
      .subscribe((tasks: ITask[]) => (this.tasksSharedCollection = tasks));

    this.scientistService
      .query()
      .pipe(map((res: HttpResponse<IScientist[]>) => res.body ?? []))
      .pipe(
        map((scientists: IScientist[]) =>
          this.scientistService.addScientistToCollectionIfMissing<IScientist>(scientists, this.area?.scientist)
        )
      )
      .subscribe((scientists: IScientist[]) => (this.scientistsSharedCollection = scientists));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-area-heading" data-cy="AreaCreateUpdateHeading">Create or edit a Area</h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_description">Description</label>
          <input
            type="text"
            class="form-control"
            name="description"
            id="field_description"
            data-cy="description"
            formControlName="description"
          />
        </div>

        <div class="row mb-3">
          <label for="field_tasks">Task</label>
          <select
            class="form-control"
            id="field_tasks"
            data-cy="task"
            multiple
            name="tasks"
            formControlName="tasks"
            [compareWith]="compareTask"
          >
            <option [ngValue]="taskOption" *ngFor="let taskOption of tasksSharedCollection">{{ taskOption.title }}</option>
          </select>
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_scientist">Scientist</label>
          <select
            class="form-control"
            id="field_scientist"
            data-cy="scientist"
            name="scientist"
            formControlName="scientist"
            [compareWith]="compareScientist"
          >
            <option [ngValue]="null"></option>
            <option [ngValue]="scientistOption" *ngFor="let scientistOption of scientistsSharedCollection">{{ scientistOption.id }}</option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// data-science-stack/src/main/webapp/app/entities/area/area-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2 id="dataScienceStackApp.area.home.createOrEditLabel" data-cy="AreaCreateUpdateHeading">Create or edit a Area</h2>
        <div>
          <div class="form-group" v-if="area.id">
            <label for="id">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="area.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="area-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="area-title"
              data-cy="title"
              :class="{ valid: !$v.area.title.$invalid, invalid: $v.area.title.$invalid }"
              v-model="$v.area.title.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="area-description">Description</label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="area-description"
              data-cy="description"
              :class="{ valid: !$v.area.description.$invalid, invalid: $v.area.description.$invalid }"
              v-model="$v.area.description.$model"
            />
          </div>
          <div class="form-group">
            <label for="area-task">Task</label>
            <select
              class="form-control"
              id="area-tasks"
              data-cy="task"
              multiple
              name="task"
              v-if="area.tasks !== undefined"
              v-model="area.tasks"
            >
              <option v-bind:value="getSelected(area.tasks, taskOption)" v-for="taskOption in tasks" :key="taskOption.id">
                {{ taskOption.title }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="area-scientist">Scientist</label>
            <select class="form-control" id="area-scientist" data-cy="scientist" name="scientist" v-model="area.scientist">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="area.scientist && scientistOption.id === area.scientist.id ? area.scientist : scientistOption"
                v-for="scientistOption in scientists"
                :key="scientistOption.id"
              >
                {{ scientistOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span>Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.area.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span>Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./area-update.component.ts"></script>
