// data-science-stack/src/main/webapp/app/entities/scientist/scientist-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, UncontrolledTooltip, Row, Col } from 'reactstrap';
import { TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './scientist.reducer';

export const ScientistDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const scientistEntity = useAppSelector(state => state.scientist.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="scientistDetailsHeading">Scientist</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">ID</span>
          </dt>
          <dd>{scientistEntity.id}</dd>
          <dt>
            <span id="firstName">First Name</span>
            <UncontrolledTooltip target="firstName">The firstname attribute.</UncontrolledTooltip>
          </dt>
          <dd>{scientistEntity.firstName}</dd>
          <dt>
            <span id="lastName">Last Name</span>
          </dt>
          <dd>{scientistEntity.lastName}</dd>
          <dt>
            <span id="email">Email</span>
          </dt>
          <dd>{scientistEntity.email}</dd>
          <dt>
            <span id="phoneNumber">Phone Number</span>
          </dt>
          <dd>{scientistEntity.phoneNumber}</dd>
          <dt>
            <span id="startDate">Start Date</span>
          </dt>
          <dd>
            {scientistEntity.startDate ? <TextFormat value={scientistEntity.startDate} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <span id="salary">Salary</span>
          </dt>
          <dd>{scientistEntity.salary}</dd>
          <dt>
            <span id="percentage">Percentage</span>
          </dt>
          <dd>{scientistEntity.percentage}</dd>
          <dt>Department</dt>
          <dd>{scientistEntity.department ? scientistEntity.department.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/scientist" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/scientist/${scientistEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default ScientistDetail;

// data-science-stack/src/main/webapp/app/entities/scientist/detail/scientist-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IScientist } from '../scientist.model';

@Component({
  selector: 'jhi-scientist-detail',
  templateUrl: './scientist-detail.component.html',
})
export class ScientistDetailComponent implements OnInit {
  scientist: IScientist | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ scientist }) => {
      this.scientist = scientist;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="scientist">
      <h2 data-cy="scientistDetailsHeading"><span>Scientist</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span>ID</span></dt>
        <dd>
          <span>{{ scientist.id }}</span>
        </dd>
        <dt><span ngbTooltip="The firstname attribute.">First Name</span></dt>
        <dd>
          <span>{{ scientist.firstName }}</span>
        </dd>
        <dt><span>Last Name</span></dt>
        <dd>
          <span>{{ scientist.lastName }}</span>
        </dd>
        <dt><span>Email</span></dt>
        <dd>
          <span>{{ scientist.email }}</span>
        </dd>
        <dt><span>Phone Number</span></dt>
        <dd>
          <span>{{ scientist.phoneNumber }}</span>
        </dd>
        <dt><span>Start Date</span></dt>
        <dd>
          <span>{{ scientist.startDate | formatMediumDatetime }}</span>
        </dd>
        <dt><span>Salary</span></dt>
        <dd>
          <span>{{ scientist.salary }}</span>
        </dd>
        <dt><span>Percentage</span></dt>
        <dd>
          <span>{{ scientist.percentage }}</span>
        </dd>
        <dt><span>Department</span></dt>
        <dd>
          <div *ngIf="scientist.department">
            <a [routerLink]="['/department', scientist.department.id, 'view']">{{ scientist.department.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
      </button>

      <button type="button" [routerLink]="['/scientist', scientist.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
      </button>
    </div>
  </div>
</div>
