// data-science-stack/src/main/webapp/app/entities/area/area-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2 id="dataScienceStackApp.area.home.createOrEditLabel" data-cy="AreaCreateUpdateHeading">Create or edit a Area</h2>
        <div>
          <div class="form-group" v-if="area.id">
            <label for="id">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="area.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="area-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="area-title"
              data-cy="title"
              :class="{ valid: !$v.area.title.$invalid, invalid: $v.area.title.$invalid }"
              v-model="$v.area.title.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="area-description">Description</label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="area-description"
              data-cy="description"
              :class="{ valid: !$v.area.description.$invalid, invalid: $v.area.description.$invalid }"
              v-model="$v.area.description.$model"
            />
          </div>
          <div class="form-group">
            <label for="area-task">Task</label>
            <select
              class="form-control"
              id="area-tasks"
              data-cy="task"
              multiple
              name="task"
              v-if="area.tasks !== undefined"
              v-model="area.tasks"
            >
              <option v-bind:value="getSelected(area.tasks, taskOption)" v-for="taskOption in tasks" :key="taskOption.id">
                {{ taskOption.title }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="area-scientist">Scientist</label>
            <select class="form-control" id="area-scientist" data-cy="scientist" name="scientist" v-model="area.scientist">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="area.scientist && scientistOption.id === area.scientist.id ? area.scientist : scientistOption"
                v-for="scientistOption in scientists"
                :key="scientistOption.id"
              >
                {{ scientistOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span>Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.area.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span>Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./area-update.component.ts"></script>

// data-science-stack-deprecated/src/main/webapp/app/entities/area/area-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { ITask } from 'app/shared/model/task.model';
import { getEntities as getTasks } from 'app/entities/task/task.reducer';
import { IScientist } from 'app/shared/model/scientist.model';
import { getEntities as getScientists } from 'app/entities/scientist/scientist.reducer';
import { IArea } from 'app/shared/model/area.model';
import { getEntity, updateEntity, createEntity, reset } from './area.reducer';

export const AreaUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const tasks = useAppSelector(state => state.task.entities);
  const scientists = useAppSelector(state => state.scientist.entities);
  const areaEntity = useAppSelector(state => state.area.entity);
  const loading = useAppSelector(state => state.area.loading);
  const updating = useAppSelector(state => state.area.updating);
  const updateSuccess = useAppSelector(state => state.area.updateSuccess);

  const handleClose = () => {
    navigate('/area' + location.search);
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getTasks({}));
    dispatch(getScientists({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...areaEntity,
      ...values,
      tasks: mapIdList(values.tasks),
      scientist: scientists.find(it => it.id.toString() === values.scientist.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          ...areaEntity,
          tasks: areaEntity?.tasks?.map(e => e.id.toString()),
          scientist: areaEntity?.scientist?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="dataScienceStackApp.area.home.createOrEditLabel" data-cy="AreaCreateUpdateHeading">
            Create or edit a Area
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? <ValidatedField name="id" required readOnly id="area-id" label="ID" validate={{ required: true }} /> : null}
              <ValidatedField label="Title" id="area-title" name="title" data-cy="title" type="text" />
              <ValidatedField label="Description" id="area-description" name="description" data-cy="description" type="text" />
              <ValidatedField label="Task" id="area-task" data-cy="task" type="select" multiple name="tasks">
                <option value="" key="0" />
                {tasks
                  ? tasks.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.title}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField id="area-scientist" name="scientist" data-cy="scientist" label="Scientist" type="select">
                <option value="" key="0" />
                {scientists
                  ? scientists.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/area" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default AreaUpdate;
