// data-science-stack/src/main/webapp/app/entities/scientist/scientist-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2 id="dataScienceStackApp.scientist.home.createOrEditLabel" data-cy="ScientistCreateUpdateHeading">Create or edit a Scientist</h2>
        <div>
          <div class="form-group" v-if="scientist.id">
            <label for="id">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="scientist.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-firstName">First Name</label>
            <input
              type="text"
              class="form-control"
              name="firstName"
              id="scientist-firstName"
              data-cy="firstName"
              :class="{ valid: !$v.scientist.firstName.$invalid, invalid: $v.scientist.firstName.$invalid }"
              v-model="$v.scientist.firstName.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-lastName">Last Name</label>
            <input
              type="text"
              class="form-control"
              name="lastName"
              id="scientist-lastName"
              data-cy="lastName"
              :class="{ valid: !$v.scientist.lastName.$invalid, invalid: $v.scientist.lastName.$invalid }"
              v-model="$v.scientist.lastName.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-email">Email</label>
            <input
              type="text"
              class="form-control"
              name="email"
              id="scientist-email"
              data-cy="email"
              :class="{ valid: !$v.scientist.email.$invalid, invalid: $v.scientist.email.$invalid }"
              v-model="$v.scientist.email.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-phoneNumber">Phone Number</label>
            <input
              type="text"
              class="form-control"
              name="phoneNumber"
              id="scientist-phoneNumber"
              data-cy="phoneNumber"
              :class="{ valid: !$v.scientist.phoneNumber.$invalid, invalid: $v.scientist.phoneNumber.$invalid }"
              v-model="$v.scientist.phoneNumber.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-startDate">Start Date</label>
            <div class="d-flex">
              <input
                id="scientist-startDate"
                data-cy="startDate"
                type="datetime-local"
                class="form-control"
                name="startDate"
                :class="{ valid: !$v.scientist.startDate.$invalid, invalid: $v.scientist.startDate.$invalid }"
                :value="convertDateTimeFromServer($v.scientist.startDate.$model)"
                @change="updateInstantField('startDate', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-salary">Salary</label>
            <input
              type="number"
              class="form-control"
              name="salary"
              id="scientist-salary"
              data-cy="salary"
              :class="{ valid: !$v.scientist.salary.$invalid, invalid: $v.scientist.salary.$invalid }"
              v-model.number="$v.scientist.salary.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-percentage">Percentage</label>
            <input
              type="number"
              class="form-control"
              name="percentage"
              id="scientist-percentage"
              data-cy="percentage"
              :class="{ valid: !$v.scientist.percentage.$invalid, invalid: $v.scientist.percentage.$invalid }"
              v-model.number="$v.scientist.percentage.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-department">Department</label>
            <select class="form-control" id="scientist-department" data-cy="department" name="department" v-model="scientist.department">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="
                  scientist.department && departmentOption.id === scientist.department.id ? scientist.department : departmentOption
                "
                v-for="departmentOption in departments"
                :key="departmentOption.id"
              >
                {{ departmentOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span>Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.scientist.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span>Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./scientist-update.component.ts"></script>

// data-science-stack/src/main/webapp/app/entities/scientist/scientist-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText, UncontrolledTooltip } from 'reactstrap';
import { isNumber, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IDepartment } from 'app/shared/model/department.model';
import { getEntities as getDepartments } from 'app/entities/department/department.reducer';
import { IScientist } from 'app/shared/model/scientist.model';
import { getEntity, updateEntity, createEntity, reset } from './scientist.reducer';

export const ScientistUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const departments = useAppSelector(state => state.department.entities);
  const scientistEntity = useAppSelector(state => state.scientist.entity);
  const loading = useAppSelector(state => state.scientist.loading);
  const updating = useAppSelector(state => state.scientist.updating);
  const updateSuccess = useAppSelector(state => state.scientist.updateSuccess);

  const handleClose = () => {
    navigate('/scientist');
  };

  useEffect(() => {
    if (!isNew) {
      dispatch(getEntity(id));
    }

    dispatch(getDepartments({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    values.startDate = convertDateTimeToServer(values.startDate);

    const entity = {
      ...scientistEntity,
      ...values,
      department: departments.find(it => it.id.toString() === values.department.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          startDate: displayDefaultDateTime(),
        }
      : {
          ...scientistEntity,
          startDate: convertDateTimeFromServer(scientistEntity.startDate),
          department: scientistEntity?.department?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="dataScienceStackApp.scientist.home.createOrEditLabel" data-cy="ScientistCreateUpdateHeading">
            Create or edit a Scientist
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? <ValidatedField name="id" required readOnly id="scientist-id" label="ID" validate={{ required: true }} /> : null}
              <ValidatedField label="First Name" id="scientist-firstName" name="firstName" data-cy="firstName" type="text" />
              <UncontrolledTooltip target="firstNameLabel">The firstname attribute.</UncontrolledTooltip>
              <ValidatedField label="Last Name" id="scientist-lastName" name="lastName" data-cy="lastName" type="text" />
              <ValidatedField label="Email" id="scientist-email" name="email" data-cy="email" type="text" />
              <ValidatedField label="Phone Number" id="scientist-phoneNumber" name="phoneNumber" data-cy="phoneNumber" type="text" />
              <ValidatedField
                label="Start Date"
                id="scientist-startDate"
                name="startDate"
                data-cy="startDate"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField label="Salary" id="scientist-salary" name="salary" data-cy="salary" type="text" />
              <ValidatedField label="Percentage" id="scientist-percentage" name="percentage" data-cy="percentage" type="text" />
              <ValidatedField id="scientist-department" name="department" data-cy="department" label="Department" type="select">
                <option value="" key="0" />
                {departments
                  ? departments.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/scientist" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default ScientistUpdate;
