// data-science-stack/src/main/webapp/app/entities/scientist/update/scientist-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { ScientistFormService, ScientistFormGroup } from './scientist-form.service';
import { IScientist } from '../scientist.model';
import { ScientistService } from '../service/scientist.service';
import { IDepartment } from 'app/entities/department/department.model';
import { DepartmentService } from 'app/entities/department/service/department.service';

@Component({
  selector: 'jhi-scientist-update',
  templateUrl: './scientist-update.component.html',
})
export class ScientistUpdateComponent implements OnInit {
  isSaving = false;
  scientist: IScientist | null = null;

  departmentsSharedCollection: IDepartment[] = [];

  editForm: ScientistFormGroup = this.scientistFormService.createScientistFormGroup();

  constructor(
    protected scientistService: ScientistService,
    protected scientistFormService: ScientistFormService,
    protected departmentService: DepartmentService,
    protected activatedRoute: ActivatedRoute
  ) {}

  compareDepartment = (o1: IDepartment | null, o2: IDepartment | null): boolean => this.departmentService.compareDepartment(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ scientist }) => {
      this.scientist = scientist;
      if (scientist) {
        this.updateForm(scientist);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const scientist = this.scientistFormService.getScientist(this.editForm);
    if (scientist.id !== null) {
      this.subscribeToSaveResponse(this.scientistService.update(scientist));
    } else {
      this.subscribeToSaveResponse(this.scientistService.create(scientist));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IScientist>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(scientist: IScientist): void {
    this.scientist = scientist;
    this.scientistFormService.resetForm(this.editForm, scientist);

    this.departmentsSharedCollection = this.departmentService.addDepartmentToCollectionIfMissing<IDepartment>(
      this.departmentsSharedCollection,
      scientist.department
    );
  }

  protected loadRelationshipsOptions(): void {
    this.departmentService
      .query()
      .pipe(map((res: HttpResponse<IDepartment[]>) => res.body ?? []))
      .pipe(
        map((departments: IDepartment[]) =>
          this.departmentService.addDepartmentToCollectionIfMissing<IDepartment>(departments, this.scientist?.department)
        )
      )
      .subscribe((departments: IDepartment[]) => (this.departmentsSharedCollection = departments));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-scientist-heading" data-cy="ScientistCreateUpdateHeading">Create or edit a Scientist</h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_firstName" ngbTooltip="The firstname attribute.">First Name</label>
          <input type="text" class="form-control" name="firstName" id="field_firstName" data-cy="firstName" formControlName="firstName" />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_lastName">Last Name</label>
          <input type="text" class="form-control" name="lastName" id="field_lastName" data-cy="lastName" formControlName="lastName" />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_email">Email</label>
          <input type="text" class="form-control" name="email" id="field_email" data-cy="email" formControlName="email" />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_phoneNumber">Phone Number</label>
          <input
            type="text"
            class="form-control"
            name="phoneNumber"
            id="field_phoneNumber"
            data-cy="phoneNumber"
            formControlName="phoneNumber"
          />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_startDate">Start Date</label>
          <div class="d-flex">
            <input
              id="field_startDate"
              data-cy="startDate"
              type="datetime-local"
              class="form-control"
              name="startDate"
              formControlName="startDate"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_salary">Salary</label>
          <input type="number" class="form-control" name="salary" id="field_salary" data-cy="salary" formControlName="salary" />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_percentage">Percentage</label>
          <input
            type="number"
            class="form-control"
            name="percentage"
            id="field_percentage"
            data-cy="percentage"
            formControlName="percentage"
          />
        </div>

        <div class="row mb-3">
          <label class="form-label" for="field_department">Department</label>
          <select
            class="form-control"
            id="field_department"
            data-cy="department"
            name="department"
            formControlName="department"
            [compareWith]="compareDepartment"
          >
            <option [ngValue]="null"></option>
            <option [ngValue]="departmentOption" *ngFor="let departmentOption of departmentsSharedCollection">
              {{ departmentOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// data-science-stack/src/main/webapp/app/entities/scientist/scientist-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2 id="dataScienceStackApp.scientist.home.createOrEditLabel" data-cy="ScientistCreateUpdateHeading">Create or edit a Scientist</h2>
        <div>
          <div class="form-group" v-if="scientist.id">
            <label for="id">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="scientist.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-firstName">First Name</label>
            <input
              type="text"
              class="form-control"
              name="firstName"
              id="scientist-firstName"
              data-cy="firstName"
              :class="{ valid: !$v.scientist.firstName.$invalid, invalid: $v.scientist.firstName.$invalid }"
              v-model="$v.scientist.firstName.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-lastName">Last Name</label>
            <input
              type="text"
              class="form-control"
              name="lastName"
              id="scientist-lastName"
              data-cy="lastName"
              :class="{ valid: !$v.scientist.lastName.$invalid, invalid: $v.scientist.lastName.$invalid }"
              v-model="$v.scientist.lastName.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-email">Email</label>
            <input
              type="text"
              class="form-control"
              name="email"
              id="scientist-email"
              data-cy="email"
              :class="{ valid: !$v.scientist.email.$invalid, invalid: $v.scientist.email.$invalid }"
              v-model="$v.scientist.email.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-phoneNumber">Phone Number</label>
            <input
              type="text"
              class="form-control"
              name="phoneNumber"
              id="scientist-phoneNumber"
              data-cy="phoneNumber"
              :class="{ valid: !$v.scientist.phoneNumber.$invalid, invalid: $v.scientist.phoneNumber.$invalid }"
              v-model="$v.scientist.phoneNumber.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-startDate">Start Date</label>
            <div class="d-flex">
              <input
                id="scientist-startDate"
                data-cy="startDate"
                type="datetime-local"
                class="form-control"
                name="startDate"
                :class="{ valid: !$v.scientist.startDate.$invalid, invalid: $v.scientist.startDate.$invalid }"
                :value="convertDateTimeFromServer($v.scientist.startDate.$model)"
                @change="updateInstantField('startDate', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-salary">Salary</label>
            <input
              type="number"
              class="form-control"
              name="salary"
              id="scientist-salary"
              data-cy="salary"
              :class="{ valid: !$v.scientist.salary.$invalid, invalid: $v.scientist.salary.$invalid }"
              v-model.number="$v.scientist.salary.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-percentage">Percentage</label>
            <input
              type="number"
              class="form-control"
              name="percentage"
              id="scientist-percentage"
              data-cy="percentage"
              :class="{ valid: !$v.scientist.percentage.$invalid, invalid: $v.scientist.percentage.$invalid }"
              v-model.number="$v.scientist.percentage.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="scientist-department">Department</label>
            <select class="form-control" id="scientist-department" data-cy="department" name="department" v-model="scientist.department">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="
                  scientist.department && departmentOption.id === scientist.department.id ? scientist.department : departmentOption
                "
                v-for="departmentOption in departments"
                :key="departmentOption.id"
              >
                {{ departmentOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span>Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.scientist.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span>Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./scientist-update.component.ts"></script>
